### ISSUE TITLE
Document Entra ID setup

### ISSUE THREAD

**Issue by hobofan** [EratoLab/erato#57]
Until we have a proper documentation page, I'll put all our findings regarding setting up Entra ID as a IDP here.

## Oauth2-proxy

It may happen that due to many claims being selected in the Entra ID application setup, the oauth2-proxy cookie grows so big that we need to increase the cookie size permitted by the ingress.

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
```

In the future, we may be able to prevent this issue if using another oauth2-proxy session storage mechanism than `memory`
